[platformio]
build_cache_dir = ../../.cache

[env:tester]
platform        = espressif32@7.0.1
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_port     = COM4
lib_deps        = foodyfood/esp32-mcp2518fd-driver
build_flags     = -DROLE_TESTER

[env:ecu]
platform        = espressif32@7.0.1
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_port     = COM3
lib_deps        = foodyfood/esp32-mcp2518fd-driver
build_flags     = -DROLE_ECU
