[env:simulator]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = foodyfood/esp32-mcp2518fd-driver
build_flags = -DROLE_SIMULATOR
upload_port = COM4
monitor_speed = 115200

[env:monitor]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = foodyfood/esp32-mcp2518fd-driver
build_flags = -DROLE_MONITOR
upload_port = COM3
monitor_speed = 115200
